// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v3.20.3

/* eslint-disable */

export * as data_gateway from "./index.data_gateway";
